services:
  - type: web
    name: projectorroom
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: projectorroom-db
          property: connectionString

databases:
  - name: projectorroom-db
    databaseName: projectorroom
    user: projectorroom
