databases:
  - name: projectorroom-db
    databaseName: projectorroom
    user: admin
    plan: free # Puedes cambiarlo a 'starter' si prefieres pago

services:
  - type: web
    name: projector-room-app
    runtime: node
    plan: free
    buildCommand: npm install
    # Este comando crea las tablas antes de arrancar la app
    preDeployCommand: node scripts/init-db.js 
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: projectorroom-db
          property: connectionString
      - key: TMDB_API_KEY
        sync: false # Deber√°s poner el valor una vez en el panel de Render
      - key: NODE_ENV
        value: production
